apply API update #9 on every stuff here

diff --git a/sched_tuner_updater/system/xbin/sched_tuner b/sched_tuner_updater/system/xbin/sched_tuner
--- a/sched_tuner_updater/system/xbin/sched_tuner
+++ b/sched_tuner_updater/system/xbin/sched_tuner
@@ -56,7 +56,7 @@ until [[ "$1" != --debug ]] && [[ "$1" != --verbose ]] && [[ "$1" != --supass ]]
 	fi
 	shift
 done
-readonly version="1.0.4"
+readonly version="1.0.5"
 readonly BASE_NAME=$(basename $0)
 readonly NO_EXTENSION=$(echo $BASE_NAME | sed 's/\..*//')
 readonly backup_PATH=$PATH
@@ -307,7 +307,11 @@ install(){
 		done
 	fi
 	echo -n -e '\rcopying files...'
-	cp $FULL_NAME $loc/$NO_EXTENSION
+	if [[ "$DIR_NAME" == NULL ]]; then
+		cp $0 $loc/$NO_EXTENSION
+	else
+		cp $FULL_NAME $loc/$NO_EXTENSION
+	fi
 	error=$?
 	chmod 755 $loc/$NO_EXTENSION
 	if [[ "$ro" == 1 ]]; then
@@ -410,6 +414,7 @@ error(){
 # 1.0.3 - more error msgs for debugging
 #       - wakelock_sheriff whitelist enabled
 # 1.0.4 - more clear instructions on how to whitelist apps added
+# 1.0.5 - thread_booster added for performance
 
 set +e #error proof
 
@@ -691,6 +696,55 @@ list_feature(){
 }
 
 
+
+thread_booster(){
+	sleep=$1
+	if [[ ! "$sleep" ]]; then
+		sleep=10
+	fi
+	if [[ "$1" == -f ]]; then
+		for i in $(pgrep -l '' | grep '\<org\.\|\<app\.\|\<com\.\|\<android\.' | grep -v -e 'android\.' | awk '{print $1}'); do
+			niceness=$(cat /proc/$i/stat)
+			niceness=${niceness#*)}
+			niceness=$(echo $niceness | awk '{print $17}')
+			if [[ "$niceness" == -20 ]]; then
+				renice 0 $i
+			fi
+		done
+		rm $external/thread_booster.cfg
+		return 0
+	fi
+	if [[ ! -f $external/thread_booster.cfg ]]; then
+		echo '#thread booster config file
+
+settings\|vending' > $external/thread_booster.cfg
+	fi
+	custom_booster=$(cat $external/thread_booster.cfg | grep -v -e '#' | tail -n1)
+	while true; do
+		for i in $(pgrep -l '' | grep '\<org\.\|\<app\.\|\<com\.\|\<android\.' | grep -v -i -e $custom_booster | awk '{print $1}'); do
+			niceness=$(cat /proc/$i/stat)
+			niceness=${niceness#*)}
+			niceness=$(echo $niceness | awk '{print $17}')
+			if [[ "$(cat /proc/$i/oom_adj)" == 0 ]]; then
+				if [[ "$niceness" != -20 ]]; then
+					renice -20 $i
+				fi
+			else
+				if [[ "$niceness" == -20 ]]; then
+					renice 0 $i
+				fi
+			fi
+		done
+		sleep $sleep
+		if [[ "$no_wakelock" == 1 ]]; then
+			until [[ "$(cat /sys/class/graphics/fb0/show_blank_event)" == "panel_power_on = 1" ]]; do
+				sleep 10
+			done
+		else
+			awake=$(cat /sys/power/wait_for_fb_wake)
+		fi
+	done & echo $! > $external/thread_booster_pid
+}
 
 
 wakelock_sheriff(){
@@ -1005,7 +1059,7 @@ Usage: $BASE_NAME -a | --activate [on/off] -h | --help | -a -m -s -w
 		;;
 		-s | --singlecorefix)
 			backup_feature
-			if [[ "$2" != -a ]]&&[[ "$2" != -m ]]&&[[ "$2" != -s ]]&&[[ "$2" != -w ]]&&[[ "$3" != -a ]]&&[[ "$3" != -m ]]&&[[ "$3" != -s ]]&&[[ "$3" != -w ]]; then
+			if [[ "$2" != -a ]]&&[[ "$2" != -m ]]&&[[ "$2" != -s ]]&&[[ "$2" != -w ]]&&[[ "$2" != -b ]]&&[[ "$3" != -a ]]&&[[ "$3" != -m ]]&&[[ "$3" != -s ]]&&[[ "$3" != -w ]]&&[[ "$3" != -b ]]; then
 				singlecorefix $2 $3
 				if [[ "$?" != 0 ]]; then
 					error something went wrong.
@@ -1025,7 +1079,7 @@ Usage: $BASE_NAME -a | --activate [on/off] -h | --help | -a -m -s -w
 		;;
 		-w | --wakelock_sheriff)
 			backup_feature
-			if [[ "$2" != -a ]]&&[[ "$2" != -m ]]&&[[ "$2" != -s ]]&&[[ "$2" != -w ]]&&[[ "$3" != -a ]]&&[[ "$3" != -m ]]&&[[ "$3" != -s ]]&&[[ "$3" != -w ]]; then
+			if [[ "$2" != -a ]]&&[[ "$2" != -m ]]&&[[ "$2" != -s ]]&&[[ "$2" != -w ]]&&[[ "$2" != -b ]]&&[[ "$3" != -a ]]&&[[ "$3" != -m ]]&&[[ "$3" != -s ]]&&[[ "$3" != -w ]]&&[[ "$3" != -b ]]; then
 				wakelock_sheriff $2 $3
 				if [[ "$?" != 0 ]]; then
 					error something went wrong.
@@ -1041,6 +1095,25 @@ Usage: $BASE_NAME -a | --activate [on/off] -h | --help | -a -m -s -w
 				fi
 			fi
 			error wakelock_sheriff init complete!
+			loop=1
+		;;
+		-b | --thread_booster)
+			backup_feature
+			if [[ "$2" != -a ]]&&[[ "$2" != -m ]]&&[[ "$2" != -s ]]&&[[ "$2" != -w ]]&&[[ "$2" != -b ]]; then
+				thread_booster $2
+				if [[ "$?" != 0 ]]; then
+					error something went wrong.
+					exit 1
+				fi
+				shift
+			else
+				thread_booster
+				if [[ "$?" != 0 ]]; then
+					error something went wrong.
+					exit 1
+				fi
+			fi
+			error thread_booster init complete!
 			loop=1
 		;;
 		-l | --list)
@@ -1116,7 +1189,7 @@ background_task(){
 	until [[ -f $FULL_NAME ]]; do
 		sleep 1
 	done
-	$FULL_NAME -a $install_rtmixman $install_singlecorefix $singlecorefix_time $singlecorefix_usage $install_wakelock_sheriff $wakelock_sheriff_time $wakelock_sheriff_usage
+	$FULL_NAME -a $install_rtmixman $install_singlecorefix $singlecorefix_time $singlecorefix_usage $install_wakelock_sheriff $wakelock_sheriff_time $wakelock_sheriff_usage $install_thread_booster $thread_booster_time
 }
 background_task & #in case the target was stored in external storage...
 
@@ -1126,7 +1199,7 @@ renice_task(){
 	until [[ \"\$(pgrep zygote)\" ]]; do
 		sleep 0.1
 	done
-	renice -20 \$(pgrep zygote)
+	renice $thread_booster_compat \$(pgrep zygote)
 	until [[ \"\$(pgrep system_server)\" ]]; do
 		sleep 0.1
 	done
@@ -1173,6 +1246,9 @@ service sched_tuner_task /system/etc/init.d/sched_tuner_task
 		fi
 	fi
 }
+
+thread_booster_compat=-20 #compat
+
 main(){
 	while true; do
 		clear
@@ -1215,15 +1291,19 @@ main(){
 		if [[ ! -f $external/wakelock_sheriff_pid ]]; then
 			echo null > $external/wakelock_sheriff_pid
 		fi
+		if [[ ! -f $external/thread_booster_pid ]]; then
+			echo null > $external/thread_booster_pid
+		fi
 		if [[ "$?" != 0 ]]; then
 			error something went wrong.
 			exit 1
 		fi
 		appliedonboot=$(ps | grep '{sched_tuner_tas}' | grep -v grep | awk '{print $1}') #good fix for multiple tasks.
-		if [[ "$appliedonboot" ]]&&[[ ! -s $external/rtmixman_pid ]]&&[[ ! -s $external/singlecorefix_pid ]]&&[[ ! -s $external/wakelock_sheriff_pid ]]; then
+		if [[ "$appliedonboot" ]]&&[[ ! -s $external/rtmixman_pid ]]&&[[ ! -s $external/singlecorefix_pid ]]&&[[ ! -s $external/wakelock_sheriff_pid ]]&&[[ ! -s $external/thread_booster_pid ]]; then
 			echo $(echo $appliedonboot | awk '{print $1}') > $external/rtmixman_pid
 			echo $(echo $appliedonboot | awk '{print $2}') > $external/singlecorefix_pid
 			echo $(echo $appliedonboot | awk '{print $3}') > $external/wakelock_sheriff_pid
+			echo $(echo $appliedonboot | awk '{print $4}') > $external/thread_booster_pid
 		fi
 		echo "realtime engines list>>"
 		if [[ "$(cat $external/rtmixman_pid)" != null ]]&&[[ "$(ps | grep "$(cat $external/rtmixman_pid)" | grep -v grep)" ]]; then
@@ -1241,17 +1321,34 @@ main(){
 		else
 			echo -e 'wakelock sheriff status: \e[1;31mnot running\e[0m'
 		fi
+		if [[ "$(cat $external/thread_booster_pid)" != null ]]&&[[ "$(ps | grep "$(cat $external/thread_booster_pid)" | grep -v grep)" ]]; then
+			thread_booster_status=1
+			echo -e 'thread booster status: \e[1;32mrunning\e[0m'
+		else
+			echo -e 'thread booster status: \e[1;31mnot running\e[0m'
+			unset thread_booster_status
+		fi
 		long_line 1
 		echo -n "boot tweaks status: "
 		if [[ "$(ps -o nice,comm | grep kswapd0 | awk '{print $1}')" == 19 ]]; then
 			if [[ "$(ps -o nice,comm | grep system_server | awk '{print $1}')" == -20 ]]; then
-				echo -e "\e[1;32mapplied!\e[0m"
+				if [[ "$thread_booster_status" == 1 ]]; then
+					echo -e "\e[1;31merror!!\e[0m
+\e[1;33mboot tweak settings are not properly configured and is causing conflicts with the following MOD:\e[0m thread_booster\e[1;33m
+please reinstall and try again.\e[0m"
+				else
+					echo -e "\e[1;32mapplied!\e[0m"
+				fi
 				boottweak=1
 			else
-				echo -e "\e[1;33mpartially applied!\e[0m
+				if [[ "$thread_booster_status" == 1 ]]; then
+					echo -e "\e[1;32musing thread booster\e[0m"
+				else
+					echo -e "\e[1;33mpartially applied!\e[0m
 
 one of these may have happened: your kernel runs this MOD too late, or newer Android versions have blocked this exploit attempt.
 or simply it could just be the result of 'soft' rebooting Android system..."
+				fi
 			fi
 		else
 			echo -e "\e[1;31mnot applied!\e[0m"
@@ -1346,7 +1443,8 @@ q)exit'
 				done
 				if [[ "$return" ]]; then
 					unset return
-					break
+					sleep 1
+					continue
 				fi
 				long_line 1
 				echo -n 'install rtmixman? Y/N:'
@@ -1376,7 +1474,8 @@ q)exit'
 				done
 				if [[ "$return" ]]; then
 					unset return
-					break
+					sleep 1
+					continue
 				fi
 				long_line 1
 				echo -n 'install scAudioFix? Y/N:'
@@ -1419,7 +1518,8 @@ q)exit'
 				unset dont
 				if [[ "$return" ]]; then
 					unset return
-					break
+					sleep 1
+					continue
 				fi
 				long_line 1
 				echo -n 'install wakelock sheriff? Y/N:'
@@ -1450,7 +1550,7 @@ q)exit'
 					echo -n press \'q\' to quit.
 				done
 				if [[ ! "$dont" ]]; then
-					echo -n 'wakelock sheriff: how many seconds interval?: (press return for default setting: 1min)>>'
+					echo -n 'wakelock sheriff: how many seconds interval?: (press return for default setting: 60secs)>>'
 					read wakelock_sheriff_time
 				fi
 				if [[ ! "$dont" ]]; then
@@ -1462,7 +1562,47 @@ q)exit'
 				unset dont
 				if [[ "$return" ]]; then
 					unset return
-					break
+					sleep 1
+					continue
+				fi
+				long_line 1
+				echo -n 'install thread booster? Y/N:'
+				while true; do
+					stty cbreak -echo
+					f=$(dd bs=1 count=1 2>/dev/null)
+					stty -cbreak echo
+					echo $f
+					case $f in
+						y* | Y*)
+							install_thread_booster="-b"
+							thread_booster_compat=0 #compat
+							break
+						;;
+						n* | N*)
+							dont=1
+							break
+						;;
+						q* | Q*)
+							echo canceled.
+							return=1
+							dont=1
+							break
+						;;
+						*)
+							checkers
+						;;
+					esac
+					echo -n press \'q\' to quit.
+				done
+				if [[ ! "$dont" ]]; then
+					echo -n 'thread booster: how many seconds interval?: (press return for default setting: 10secs)>>'
+					read thread_booster_time
+				fi
+				unset dont
+				if [[ "$return" ]]; then
+					unset return
+					sleep 1
+					continue
 				fi
 				long_line 1
 				echo -n 'setting on boot...'
@@ -1474,7 +1614,28 @@ q)exit'
 				unset install_wakelock_sheriff
 				unset wakelock_sheriff_time
 				unset wakelock_sheriff_usage
-				echo done!
+				unset install_thread_booster
+				unset thread_booster_time
+				echo done! reboot system to take effect!!
+				echo would you like to reboot? Y/N:
+				stty cbreak -echo
+				f=$(dd bs=1 count=1 2>/dev/null)
+				stty -cbreak echo
+				echo $f
+				case $f in
+					y* | Y*)
+						echo 16 > /proc/sys/kernel/sysrq 2>/dev/null # 0x10 //sync
+						echo s > /proc/sysrq-trigger 2>/dev/null
+						sync 2>/dev/null
+						echo 128 > /proc/sys/kernel/sysrq 2>/dev/null # 0x80 //reboot
+						echo b > /proc/sysrq-trigger 2>/dev/null
+						reboot 2>/dev/null
+						error something went wrong, please reboot manually!
+					;;
+					*)
+						echo canceled.
+					;;
+				esac
 				sleep 5
 			;;
 			3)
@@ -1518,7 +1679,7 @@ q)exit'
 					kill -9 $(cat $external/wakelock_sheriff_pid)
 					wakelock_sheriff -f
 				else
-					echo -n 'how many seconds interval?: (press return for default setting: 1min)>>'
+					echo -n 'how many seconds interval?: (press return for default setting: 60secs)>>'
 					read time
 					echo 'Garbageprocess Disposer - in how much cpu usage should the Disposer limit?(out of 100% cpu usage):'
 					echo 'tip - LOWEST IS THE BEST. (press return for default setting: 0%)'
@@ -1538,6 +1699,8 @@ q)exit'
 			6)
 				echo -n restoring backup...
 				apply_backup
+				kill -9 $(cat $external/thread_booster_pid) 2>/dev/null
+				thread_booster -f 2>/dev/null
 				if [[ "$?" != 0 ]]; then
 					echo -e '\rcould not restore backup.'
 					return 1
@@ -1578,7 +1741,14 @@ similar mechanism as scAudioFix, except:
 >>faster cycle thanks to my own advanced algorithm(completes cycle in less than quarter a second!)
 >>etc...\e[0m
 \e[1;33meven if the cycle is fast enough, cpu may wake up periodically from this engine too.
-its recommended to set a longer sleep time(default: 1 min)\e[0m'
+its recommended to set a longer sleep time(default: 1 min)\e[0m
+
+-thread booster: continuation of my older project(thread priority booster beta: http://forum.xda-developers.com/showthread.php?t=2076101)
+this will boost foreground applications to have more cpu resources than any other, resulting in smoother and less laggy performance!'
+			long_line 1
+			echo -e "thread booster \e[1;31mCANNOT\e[0m be launched directly, it must be set to run \e[1;33mON BOOT\e[0m.
+this is because thread booster may have settings that conflict with boot tweaks.
+"
 			echo -e "wakelock_sheriff.cfg whitelist can be found on $external, please read the instructions there. :3
 most important configuration files also can be found in the same directory. \e[1;31mDO NOT CORRUPT OR DELETE!!\e[0m"
 			part_line press any key to continue...
@@ -1592,6 +1762,7 @@ most important configuration files also can be found in the same directory. \e[1
 			;;
 			9| q |Q)
 				echo check out \'flag_tuner\' by Pizza_Dox@xda, highly recommended for perfect combination!:D
+				echo official forum: http://forum.xda-developers.com/android/software-hacking/script-scheduling-performance-tuner-t3029984 i dont fuck with trolls.
 				return 0
 			;;
 			*)
